### ISSUE TITLE
Баг с автогенерацией проекта + неверен путь к файлу index.html

### ISSUE THREAD

**Issue by CB9TOIIIA** [code-orchestra/colt-ui#3]
Собственно неверно создает путь к проекту (точнее верно, но нужен относительный наверно) - баг воспроизводил через ST3.

Пример на видео (публично только тем, у кого есть ссылка): 
http://youtu.be/-afiOLDyxRs

Файл видео можно сказать тут [11метров] = http://www.load.to/g2smZEDxAI/bandicam_2014-04-09_17-13-48-381.zip

**Comment by CB9TOIIIA** [comment]
Точно, на видео видно, что он генерит файл проекта в папке: C:\Users\CB9TOIIIA\Documents\GitHub\WebDeveloperJoomla\overlay\javascript

Но не в этой: I:\bootstrap (откуда запускается index.html)

**Comment by makc** [comment]
по идее эти коммиты должны поправить дело. плагин лучше не обновлять, а снести и установить заново (мы пока не научились уведомлять package control об апдейтах)

**Comment by CB9TOIIIA** [comment]
работает корректно! :) молодцы! Спасибо!
