### ISSUE TITLE
Can't select main document when start COLT from WebStorm

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-ui#4]
It seems that value from main document is not remembered. Try to select it from your file explorer, then go to console, return back - value is gone.

![alt text](http://habrastorage.org/files/c80/cd0/326/c80cd0326a66491790122a581a17946b.gif)

**Comment by dolph1n** [comment]
Please download new version (beta 11) and check this problem.

**Comment by webuniverseio** [comment]
Not sure what is going on. Please take a look:
![node.js](http://habrastorage.org/files/e19/13d/5a6/e1913d5a683e433c9de7b22fa69ec9d4.gif)

**Comment by dolph1n** [comment]
bug fixed in plugin version 1.1.4 (now it wait for approve)

**Comment by dolph1n** [comment]
new version approved. you can update and check

**Comment by webuniverseio** [comment]
Thanks, seems to launch now.
